import { motion } from 'framer-motion';
import { Brain, Dumbbell, Utensils, Volume2, ImageIcon, FileText, Sparkles } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    description: 'Personalized workout and diet plans generated by advanced AI based on your unique profile.',
  },
  {
    icon: Dumbbell,
    title: 'Custom Workouts',
    description: 'Tailored exercises for home, gym, or outdoor with sets, reps, and rest times.',
  },
  {
    icon: Utensils,
    title: 'Diet Planning',
    description: 'Complete meal plans matching your dietary preferences and fitness goals.',
  },
  {
    icon: Volume2,
    title: 'Voice Guidance',
    description: 'Listen to your plans with professional voice narration powered by ElevenLabs.',
  },
  {
    icon: ImageIcon,
    title: 'Visual Demos',
    description: 'AI-generated images for exercises and meals to guide you perfectly.',
  },
  {
    icon: FileText,
    title: 'Export as PDF',
    description: 'Download your personalized plans to access them anytime, anywhere.',
  },
];

export function Features() {
  return (
    <section className="py-24 px-4 relative">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_50%,hsl(82_100%_50%/0.05),transparent_40%)]" />
      
      <div className="max-w-6xl mx-auto relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />
            Features
          </span>
          <h2 className="font-display text-4xl md:text-5xl font-bold tracking-tight mb-4">
            Everything You Need
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            A complete fitness companion powered by cutting-edge AI technology
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="glass-card p-6 card-hover group"
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <feature.icon className="w-6 h-6 text-primary" />
              </div>
              <h3 className="font-display text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
